/**
 * The demo garment catalog — one entry per photographed piece.
 *
 * Shared by generate-images.mjs (which photographs each `key` once into
 * scripts/demo/assets/{key}.webp) and seed.mjs (which files them into the 15 demo
 * wardrobes). Field names and values match the `items` columns and the enums in
 * types/index.ts; `category` is a system category slug.
 *
 * `g` is who the piece is written for: w, m, or u (either).
 */

/** @typedef {'top'|'bottom'|'fullbody'|'outerwear'|'footwear'|'accessory'} Slot */

export const CATALOG = [
  // ─────────────────────────────── tops
  { key: 'white-oxford-shirt', g: 'm', name: 'White Short-Sleeve Shirt', category: 'tops', slot: 'top', subtype: 'shirt', style: 'casual', color: 'white', hex: '#F4F2EC', pattern: 'solid', material: 'cotton', formality: 3, warmth: 2, seasons: ['all'], brand: 'Van Heusen', retailer: 'Myntra', price: 1899, prompt: 'a crisp white cotton oxford button-down shirt, long sleeves, neatly folded collar' },
  { key: 'light-blue-linen-shirt', g: 'm', name: 'Sky Oxford Shirt', category: 'tops', slot: 'top', subtype: 'shirt', style: 'casual', color: 'light blue', hex: '#A9C4DE', pattern: 'solid', material: 'cotton', formality: 3, warmth: 1, seasons: ['summer'], brand: 'Fabindia', retailer: 'Fabindia', price: 2290, prompt: 'a light sky-blue linen shirt with a relaxed fit, slightly textured linen weave' },
  { key: 'navy-polo', g: 'm', name: 'Navy Piqué Polo', category: 'tops', slot: 'top', subtype: 'shirt', style: 'casual', color: 'navy', hex: '#1F2A44', pattern: 'solid', material: 'cotton', formality: 3, warmth: 2, seasons: ['all'], brand: 'U.S. Polo Assn.', retailer: 'Ajio', price: 1499, prompt: 'a navy blue cotton pique polo shirt with a three-button placket' },
  { key: 'grey-crew-tee', g: 'u', name: 'Pale Blue Tee', category: 'tops', slot: 'top', subtype: 't-shirt', style: 'casual', color: 'light blue', hex: '#A9BCCB', pattern: 'solid', material: 'cotton', formality: 1, warmth: 1, seasons: ['all'], brand: 'Uniqlo', retailer: 'Uniqlo', price: 790, prompt: 'a heather grey crew-neck cotton t-shirt' },
  { key: 'black-crew-tee', g: 'u', name: 'Essential Black Tee', category: 'tops', slot: 'top', subtype: 't-shirt', style: 'casual', color: 'black', hex: '#1B1B1B', pattern: 'solid', material: 'cotton', formality: 2, warmth: 1, seasons: ['all'], brand: 'H&M', retailer: 'H&M', price: 699, prompt: 'a plain black crew-neck cotton t-shirt' },
  { key: 'olive-henley', g: 'm', name: 'Olive Camp Shirt', category: 'tops', slot: 'top', subtype: 'shirt', style: 'casual', color: 'olive', hex: '#5E6B3A', pattern: 'solid', material: 'cotton', formality: 2, warmth: 2, seasons: ['all'], brand: 'Snitch', retailer: 'Snitch', price: 999, prompt: 'an olive green long-sleeve cotton henley with a short button placket' },
  { key: 'charcoal-hoodie', g: 'u', name: 'Grey Pullover Hoodie', category: 'tops', slot: 'top', subtype: 'hoodie', style: 'lounge', color: 'grey', hex: '#B9B9B7', pattern: 'solid', material: 'fleece', formality: 1, warmth: 4, seasons: ['winter', 'monsoon'], brand: 'The Souled Store', retailer: 'The Souled Store', price: 1599, prompt: 'a charcoal grey pullover hoodie with a kangaroo pocket and drawstrings' },
  { key: 'cream-cable-sweater', g: 'u', name: 'Cream Cable Knit', category: 'tops', slot: 'top', subtype: 'sweater', style: 'casual', color: 'cream', hex: '#EDE3CF', pattern: 'textured', material: 'wool', formality: 3, warmth: 4, seasons: ['winter'], brand: 'Marks & Spencer', retailer: 'Marks & Spencer', price: 2999, prompt: 'a cream cable-knit wool crewneck sweater' },
  { key: 'beige-kurta', g: 'm', name: 'Butter Cotton Kurta', category: 'tops', slot: 'top', subtype: 'shirt', style: 'formal', color: 'butter yellow', hex: '#EAD99A', pattern: 'solid', material: 'cotton', formality: 4, warmth: 2, seasons: ['all'], brand: 'Manyavar', retailer: 'Manyavar', price: 2499, prompt: 'a beige knee-length cotton kurta with a mandarin collar and subtle tonal embroidery at the placket' },
  { key: 'striped-breton-top', g: 'w', name: 'Breton Stripe Top', category: 'tops', slot: 'top', subtype: 't-shirt', style: 'casual', color: 'white', hex: '#F2F0EA', pattern: 'striped', material: 'cotton', formality: 2, warmth: 2, seasons: ['all'], brand: 'Zara', retailer: 'Zara', price: 1590, prompt: 'a white and navy horizontally striped breton long-sleeve top with a boat neck' },
  { key: 'ivory-silk-blouse', g: 'w', name: 'Ivory Satin Blouse', category: 'tops', slot: 'top', subtype: 'blouse', style: 'business', color: 'ivory', hex: '#F3EDE0', pattern: 'solid', material: 'satin', formality: 4, warmth: 1, seasons: ['all'], brand: 'Mango', retailer: 'Myntra', price: 2590, prompt: 'an ivory satin blouse with soft sheen, long sleeves and a relaxed drape' },
  { key: 'black-fitted-tee', g: 'w', name: 'Black Fitted Tee', category: 'tops', slot: 'top', subtype: 't-shirt', style: 'casual', color: 'black', hex: '#1A1A1A', pattern: 'solid', material: 'cotton', formality: 2, warmth: 1, seasons: ['all'], brand: 'Uniqlo', retailer: 'Uniqlo', price: 790, prompt: "a black women's fitted short-sleeve cotton t-shirt" },
  { key: 'white-cotton-kurti', g: 'w', name: 'Mint Chikankari Kurta', category: 'tops', slot: 'top', subtype: 'blouse', style: 'casual', color: 'mint', hex: '#BFD8C8', pattern: 'textured', material: 'cotton', formality: 3, warmth: 1, seasons: ['summer'], brand: 'W', retailer: 'Myntra', price: 1799, prompt: 'a white cotton kurti with delicate white chikankari hand embroidery' },
  { key: 'mustard-knit-top', g: 'w', name: 'Mustard Ribbed Knit', category: 'tops', slot: 'top', subtype: 'sweater', style: 'casual', color: 'mustard', hex: '#C9962E', pattern: 'textured', material: 'knit', formality: 2, warmth: 3, seasons: ['winter', 'monsoon'], brand: 'Only', retailer: 'Ajio', price: 1399, prompt: 'a mustard yellow ribbed knit long-sleeve top' },
  { key: 'dusty-pink-shirt', g: 'w', name: 'Blush Relaxed Tee', category: 'tops', slot: 'top', subtype: 't-shirt', style: 'casual', color: 'blush', hex: '#D8BBAE', pattern: 'solid', material: 'viscose', formality: 2, warmth: 1, seasons: ['all'], brand: 'Van Heusen Woman', retailer: 'Myntra', price: 1699, prompt: "a dusty rose pink women's button-up shirt with a soft drape" },

  // ─────────────────────────────── bottoms
  { key: 'indigo-slim-jeans', g: 'm', name: 'Mid-Blue Slim Jeans', category: 'bottoms', slot: 'bottom', subtype: 'jeans', style: 'casual', color: 'blue', hex: '#3E5E8A', pattern: 'solid', material: 'denim', formality: 2, warmth: 3, seasons: ['all'], brand: "Levi's", retailer: "Levi's", price: 3299, prompt: 'dark indigo slim-fit denim jeans, folded neatly' },
  { key: 'khaki-chinos', g: 'm', name: 'Khaki Chinos', category: 'bottoms', slot: 'bottom', subtype: 'trousers', style: 'business', color: 'khaki', hex: '#BFA97F', pattern: 'solid', material: 'cotton', formality: 3, warmth: 2, seasons: ['all'], brand: 'Marks & Spencer', retailer: 'Marks & Spencer', price: 2499, prompt: 'khaki cotton chino trousers' },
  { key: 'charcoal-trousers', g: 'm', name: 'Grey Relaxed Trousers', category: 'bottoms', slot: 'bottom', subtype: 'trousers', style: 'formal', color: 'grey', hex: '#8E8F92', pattern: 'solid', material: 'wool blend', formality: 5, warmth: 3, seasons: ['all'], brand: 'Raymond', retailer: 'Raymond', price: 3999, prompt: 'charcoal grey tailored wool-blend dress trousers with a sharp crease' },
  { key: 'black-joggers', g: 'u', name: 'Black Joggers', category: 'bottoms', slot: 'bottom', subtype: 'pants', style: 'lounge', color: 'black', hex: '#1D1D1F', pattern: 'solid', material: 'cotton', formality: 1, warmth: 3, seasons: ['all'], brand: 'Decathlon', retailer: 'Decathlon', price: 999, prompt: 'black tapered cotton jogger pants with cuffed ankles' },
  { key: 'navy-shorts', g: 'm', name: 'Aqua Swim Shorts', category: 'bottoms', slot: 'bottom', subtype: 'shorts', style: 'casual', color: 'aqua', hex: '#3BA3C9', pattern: 'solid', material: 'cotton', formality: 2, warmth: 1, seasons: ['summer'], brand: 'H&M', retailer: 'H&M', price: 1299, prompt: 'navy blue cotton chino shorts' },
  { key: 'high-waist-blue-jeans', g: 'w', name: 'High-Rise Straight Jeans', category: 'bottoms', slot: 'bottom', subtype: 'jeans', style: 'casual', color: 'blue', hex: '#5A7BA6', pattern: 'solid', material: 'denim', formality: 2, warmth: 3, seasons: ['all'], brand: 'Zara', retailer: 'Zara', price: 2990, prompt: 'mid-blue high-waisted straight-leg denim jeans' },
  { key: 'black-tailored-trousers', g: 'w', name: 'Black Slim Trousers', category: 'bottoms', slot: 'bottom', subtype: 'trousers', style: 'business', color: 'black', hex: '#1C1C1C', pattern: 'solid', material: 'crepe', formality: 4, warmth: 2, seasons: ['all'], brand: 'Mango', retailer: 'Myntra', price: 2790, prompt: "black women's high-waisted tailored wide-leg trousers" },
  { key: 'pleated-midi-skirt', g: 'w', name: 'Cream Pleated Midi Skirt', category: 'bottoms', slot: 'bottom', subtype: 'skirt', style: 'date-night', color: 'cream', hex: '#EDE6D6', pattern: 'solid', material: 'satin', formality: 3, warmth: 1, seasons: ['summer', 'monsoon'], brand: 'Vero Moda', retailer: 'Ajio', price: 1999, prompt: 'a sage green satin pleated midi skirt' },
  { key: 'linen-wide-pants', g: 'w', name: 'Blush Linen Pants', category: 'bottoms', slot: 'bottom', subtype: 'pants', style: 'casual', color: 'blush', hex: '#D9B8B4', pattern: 'solid', material: 'linen', formality: 2, warmth: 1, seasons: ['summer'], brand: 'Fabindia', retailer: 'Fabindia', price: 1890, prompt: 'oatmeal beige linen wide-leg drawstring pants' },
  { key: 'black-leggings', g: 'w', name: 'Black Yoga Leggings', category: 'activewear', slot: 'bottom', subtype: 'yoga pants', style: 'workout', color: 'black', hex: '#161616', pattern: 'solid', material: 'spandex', formality: 1, warmth: 2, seasons: ['all'], brand: 'Nike', retailer: 'Nike', price: 2495, prompt: 'black high-waisted performance yoga leggings' },
  { key: 'grey-running-shorts', g: 'm', name: 'Grey Running Shorts', category: 'activewear', slot: 'bottom', subtype: 'athletic shorts', style: 'workout', color: 'grey', hex: '#7D8085', pattern: 'solid', material: 'polyester', formality: 1, warmth: 1, seasons: ['all'], brand: 'Puma', retailer: 'Puma', price: 1299, prompt: 'grey lightweight running shorts with a small reflective logo' },

  // ─────────────────────────────── dresses
  { key: 'floral-midi-dress', g: 'w', name: 'Peach Floral Tea Dress', category: 'dresses', slot: 'fullbody', subtype: 'casual dress', style: 'date-night', color: 'peach', hex: '#EBCDB4', pattern: 'printed', material: 'viscose', formality: 3, warmth: 1, seasons: ['summer', 'monsoon'], brand: 'Label Ritu Kumar', retailer: 'Myntra', price: 4990, prompt: 'a navy wrap midi dress with a small white and pink floral print' },
  { key: 'black-slip-dress', g: 'w', name: 'Black Satin Slip Dress', category: 'dresses', slot: 'fullbody', subtype: 'formal dress', style: 'party', color: 'black', hex: '#141414', pattern: 'solid', material: 'satin', formality: 4, warmth: 1, seasons: ['all'], brand: 'Zara', retailer: 'Zara', price: 3590, prompt: 'a black satin bias-cut slip midi dress with thin straps' },
  { key: 'mustard-anarkali', g: 'w', name: 'Pink Block-Print Anarkali', category: 'dresses', slot: 'fullbody', subtype: 'maxi dress', style: 'formal', color: 'pink', hex: '#E08CA3', pattern: 'printed', material: 'cotton', formality: 4, warmth: 2, seasons: ['all'], brand: 'Biba', retailer: 'Biba', price: 3499, prompt: 'a mustard yellow flared anarkali kurta with a gold block-printed border' },
  { key: 'white-sundress', g: 'w', name: 'White Cotton Sundress', category: 'dresses', slot: 'fullbody', subtype: 'mini dress', style: 'casual', color: 'white', hex: '#F6F4EF', pattern: 'solid', material: 'cotton', formality: 2, warmth: 1, seasons: ['summer'], brand: 'H&M', retailer: 'H&M', price: 1999, prompt: 'a white cotton sundress with a smocked bodice and short flutter sleeves' },
  { key: 'emerald-saree', g: 'w', name: 'Emerald Silk Lehenga Set', category: 'dresses', slot: 'fullbody', subtype: 'formal dress', style: 'formal', color: 'emerald', hex: '#1F6B52', pattern: 'textured', material: 'silk', formality: 5, warmth: 2, seasons: ['all'], brand: 'Nalli', retailer: 'Nalli', price: 12500, prompt: 'an emerald green silk saree with a gold zari border, neatly folded to show the border' },

  // ─────────────────────────────── outerwear
  { key: 'navy-blazer', g: 'm', name: 'Navy Unstructured Blazer', category: 'outerwear', slot: 'outerwear', subtype: 'jacket', style: 'business', color: 'navy', hex: '#1E2940', pattern: 'solid', material: 'wool blend', formality: 5, warmth: 3, seasons: ['all'], brand: 'Arrow', retailer: 'Arrow', price: 6999, prompt: "a navy blue single-breasted men's blazer, unstructured" },
  { key: 'denim-jacket', g: 'u', name: 'Washed Denim Jacket', category: 'outerwear', slot: 'outerwear', subtype: 'jacket', style: 'casual', color: 'blue', hex: '#6D8DB3', pattern: 'solid', material: 'denim', formality: 2, warmth: 3, seasons: ['winter', 'monsoon'], brand: "Levi's", retailer: "Levi's", price: 3999, prompt: 'a light-wash blue denim trucker jacket' },
  { key: 'olive-bomber', g: 'm', name: 'Olive Field Jacket', category: 'outerwear', slot: 'outerwear', subtype: 'jacket', style: 'casual', color: 'olive', hex: '#4F5A36', pattern: 'solid', material: 'nylon', formality: 2, warmth: 3, seasons: ['winter'], brand: 'Roadster', retailer: 'Myntra', price: 2299, prompt: 'an olive green nylon bomber jacket with ribbed cuffs and collar' },
  { key: 'camel-trench', g: 'w', name: 'Camel Trench Coat', category: 'outerwear', slot: 'outerwear', subtype: 'coat', style: 'business', color: 'camel', hex: '#B88A57', pattern: 'solid', material: 'cotton gabardine', formality: 4, warmth: 3, seasons: ['winter', 'monsoon'], brand: 'Marks & Spencer', retailer: 'Marks & Spencer', price: 7999, prompt: 'a classic camel double-breasted trench coat with a belt' },
  { key: 'black-leather-jacket', g: 'u', name: 'Black Leather Jacket', category: 'outerwear', slot: 'outerwear', subtype: 'jacket', style: 'party', color: 'black', hex: '#181818', pattern: 'solid', material: 'leather', formality: 3, warmth: 3, seasons: ['winter'], brand: 'Bare Leather', retailer: 'Ajio', price: 8999, prompt: 'a black leather biker jacket with silver zips' },
  { key: 'grey-cardigan', g: 'w', name: 'Grey Soft Cardigan', category: 'outerwear', slot: 'outerwear', subtype: 'cardigan', style: 'casual', color: 'grey', hex: '#A3A19E', pattern: 'solid', material: 'knit', formality: 2, warmth: 3, seasons: ['winter', 'monsoon'], brand: 'Uniqlo', retailer: 'Uniqlo', price: 1990, prompt: 'a soft grey button-front knit cardigan' },
  { key: 'nehru-jacket', g: 'm', name: 'Maroon Nehru Jacket', category: 'outerwear', slot: 'outerwear', subtype: 'vest', style: 'formal', color: 'maroon', hex: '#6B1F2A', pattern: 'textured', material: 'silk blend', formality: 5, warmth: 2, seasons: ['all'], brand: 'Manyavar', retailer: 'Manyavar', price: 3999, prompt: 'a maroon textured silk-blend sleeveless Nehru jacket with a mandarin collar' },

  // ─────────────────────────────── footwear
  { key: 'white-sneakers', g: 'u', name: 'White Leather Sneakers', category: 'shoes', slot: 'footwear', subtype: 'sneakers', style: 'casual', color: 'white', hex: '#F3F3F1', pattern: 'solid', material: 'leather', formality: 2, warmth: 2, seasons: ['all'], brand: 'Adidas', retailer: 'Adidas', price: 6999, prompt: 'a pair of minimal white leather low-top sneakers' },
  { key: 'brown-loafers', g: 'm', name: 'Tan Penny Loafers', category: 'shoes', slot: 'footwear', subtype: 'flats', style: 'business', color: 'tan', hex: '#8B5A2B', pattern: 'solid', material: 'leather', formality: 4, warmth: 2, seasons: ['all'], brand: 'Clarks', retailer: 'Clarks', price: 5999, prompt: 'a pair of tan brown leather penny loafers' },
  { key: 'black-oxfords', g: 'm', name: 'Black Oxford Shoes', category: 'shoes', slot: 'footwear', subtype: 'flats', style: 'formal', color: 'black', hex: '#141414', pattern: 'solid', material: 'leather', formality: 5, warmth: 2, seasons: ['all'], brand: 'Hush Puppies', retailer: 'Bata', price: 4999, prompt: 'a pair of polished black leather cap-toe oxford dress shoes' },
  { key: 'running-shoes', g: 'u', name: 'Running Shoes', category: 'shoes', slot: 'footwear', subtype: 'sneakers', style: 'workout', color: 'grey', hex: '#6F7479', pattern: 'solid', material: 'mesh', formality: 1, warmth: 2, seasons: ['all'], brand: 'Asics', retailer: 'Asics', price: 7499, prompt: 'a pair of grey mesh running shoes with a white sole' },
  { key: 'chelsea-boots', g: 'm', name: 'Brown Suede Chelsea Boots', category: 'shoes', slot: 'footwear', subtype: 'boots', style: 'casual', color: 'brown', hex: '#6B4A2F', pattern: 'solid', material: 'suede', formality: 3, warmth: 3, seasons: ['winter'], brand: 'Red Tape', retailer: 'Ajio', price: 3999, prompt: 'a pair of brown suede chelsea boots' },
  { key: 'block-heels', g: 'w', name: 'Nude Block Heels', category: 'shoes', slot: 'footwear', subtype: 'heels', style: 'business', color: 'nude', hex: '#D2B49C', pattern: 'solid', material: 'faux leather', formality: 4, warmth: 1, seasons: ['all'], brand: 'Aldo', retailer: 'Aldo', price: 4999, prompt: 'a pair of nude beige block-heel pumps' },
  { key: 'tan-sandals', g: 'w', name: 'Tan Strappy Sandals', category: 'shoes', slot: 'footwear', subtype: 'sandals', style: 'casual', color: 'tan', hex: '#A77B4F', pattern: 'solid', material: 'leather', formality: 2, warmth: 1, seasons: ['summer', 'monsoon'], brand: 'Metro', retailer: 'Metro', price: 1990, prompt: 'a pair of tan leather flat strappy sandals' },
  { key: 'gold-juttis', g: 'w', name: 'Gold Embroidered Juttis', category: 'shoes', slot: 'footwear', subtype: 'flats', style: 'formal', color: 'gold', hex: '#C9A24A', pattern: 'textured', material: 'leather', formality: 4, warmth: 1, seasons: ['all'], brand: 'Fizzy Goblet', retailer: 'Fizzy Goblet', price: 2490, prompt: 'a pair of gold embroidered Punjabi jutti flats' },
  { key: 'black-ankle-boots', g: 'w', name: 'Black Ankle Boots', category: 'shoes', slot: 'footwear', subtype: 'boots', style: 'party', color: 'black', hex: '#161616', pattern: 'solid', material: 'leather', formality: 3, warmth: 3, seasons: ['winter'], brand: 'Steve Madden', retailer: 'Myntra', price: 6490, prompt: 'a pair of black leather heeled ankle boots' },

  // ─────────────────────────────── accessories
  { key: 'leather-watch', g: 'u', name: 'Brown Leather Watch', category: 'accessories', slot: 'accessory', subtype: 'jewelry', style: 'business', color: 'brown', hex: '#5C3B22', pattern: 'solid', material: 'leather', formality: 4, warmth: null, seasons: ['all'], brand: 'Titan', retailer: 'Titan', price: 5495, prompt: 'an analog wristwatch with a white dial and brown leather strap' },
  { key: 'brown-belt', g: 'm', name: 'Brown Leather Belt', category: 'accessories', slot: 'accessory', subtype: 'belt', style: 'business', color: 'brown', hex: '#6A4428', pattern: 'solid', material: 'leather', formality: 4, warmth: null, seasons: ['all'], brand: 'Woodland', retailer: 'Woodland', price: 1495, prompt: 'a coiled brown leather belt with a brushed silver buckle' },
  { key: 'canvas-backpack', g: 'u', name: 'Canvas Backpack', category: 'accessories', slot: 'accessory', subtype: 'bag', style: 'casual', color: 'olive', hex: '#6B6A4A', pattern: 'solid', material: 'canvas', formality: 1, warmth: null, seasons: ['all'], brand: 'Wildcraft', retailer: 'Wildcraft', price: 2299, prompt: 'an olive canvas backpack with tan leather trims' },
  { key: 'aviator-sunglasses', g: 'u', name: 'Aviator Sunglasses', category: 'accessories', slot: 'accessory', subtype: 'jewelry', style: 'casual', color: 'gold', hex: '#B8963E', pattern: 'solid', material: 'metal', formality: 2, warmth: null, seasons: ['summer'], brand: 'Ray-Ban', retailer: 'Lenskart', price: 7990, prompt: 'a pair of gold-frame aviator sunglasses with green lenses' },
  { key: 'tan-tote', g: 'w', name: 'Tan Leather Tote', category: 'accessories', slot: 'accessory', subtype: 'bag', style: 'business', color: 'tan', hex: '#A8743F', pattern: 'solid', material: 'leather', formality: 3, warmth: null, seasons: ['all'], brand: 'Hidesign', retailer: 'Hidesign', price: 6495, prompt: 'a structured tan leather tote bag' },
  { key: 'gold-hoops', g: 'w', name: 'Gold Hoop Earrings', category: 'accessories', slot: 'accessory', subtype: 'jewelry', style: 'date-night', color: 'gold', hex: '#C9A547', pattern: 'solid', material: 'metal', formality: 3, warmth: null, seasons: ['all'], brand: 'Accessorize', retailer: 'Accessorize', price: 999, prompt: 'a pair of medium gold hoop earrings' },
  { key: 'silk-scarf', g: 'w', name: 'Purple Chain-Print Scarf', category: 'accessories', slot: 'accessory', subtype: 'scarf', style: 'business', color: 'purple', hex: '#5E2A74', pattern: 'printed', material: 'silk', formality: 3, warmth: null, seasons: ['all'], brand: 'Satya Paul', retailer: 'Tata CLiQ', price: 2995, prompt: 'a rust and cream printed silk square scarf, loosely folded' },
  { key: 'black-crossbody', g: 'w', name: 'Black Crossbody Bag', category: 'accessories', slot: 'accessory', subtype: 'bag', style: 'party', color: 'black', hex: '#151515', pattern: 'solid', material: 'leather', formality: 3, warmth: null, seasons: ['all'], brand: 'Lavie', retailer: 'Myntra', price: 2499, prompt: 'a small black leather crossbody bag with a gold chain strap' },
];

export const byKey = Object.fromEntries(CATALOG.map((c) => [c.key, c]));
